// <auto-generated />
namespace Crawler.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _3rd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_3rd));
        
        string IMigrationMetadata.Id
        {
            get { return "201804211559174_3rd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
